### ISSUE TITLE
Facing linking error

### ISSUE THREAD

**Issue by ChandraPrakashJangid** [geopapyrus/face-recognition-sdk#1]
Please have a look at my issue..
![screen shot 2013-09-17 at 10 24 54 am](https://f.cloud.github.com/assets/4987368/1154751/5636b046-1f55-11e3-8efe-8cffefe94fd9.png)

**Comment by mital87** [comment]
I am facing same error. please update you static library file.

**Comment by geopapyrus** [comment]
The issue happens because you are building the app targeting the simulator. Change the target to an iPhone / iPad device and it should work.
